imports_granularity="Crate"
format_code_in_doc_comments = true

brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"

fn_single_line = true
where_single_line = true

blank_lines_upper_bound = 2
inline_attribute_width = 32

reorder_impl_items = true
group_imports = "StdExternalCrate"

enum_discrim_align_threshold = 16
struct_field_align_threshold = 16











